#languageCode = "en-us"
languageCode = "ko-kr"
title = "bluedskim.github.io"
baseurl = "https://bluedskim.github.io/"
#theme = "2_hugo-theme-bleak"
theme = "1_ananke"
#theme = "gohugo-amp"
#theme = "hugo-theme-minos"
publishDir = "../bluedskim.github.io"
paginate = 10

[taxonomies]
#  category = "categories"
  tag = "tags"
  
[params]
featured_image = "/images/screen2017-10-02-23-00-01.jpg"
env = "production"

#hugo-theme-minos
#[params]
#    googleAnalytics = "UA-108812986-1"
#    smartToc = true
#    adsensePublisher = "ca-pub-5002590800077159"
